config/routes.rb
Rails.application.routes.draw do
  
  

  
  get '/favicon.ico' => 'main#favicon'
  
 
    
    get '/sda' => 'sda#index', as: :sda_user_root
    devise_for :sda_users, 
         path: "sda",
      class_name: "SdaUser",
      controllers: {
        sessions: "sda/users/sessions",
        registrations: "sda/users/registrations",
        confirmations: "sda/users/confirmations",
        passwords: "sda/users/passwords",
        unlocks: "sda/users/unlocks"
      }
 
    as :sda_user do
      get '/sda/login' => 'sda/users/sessions#new', :as => :new_user_session
      post '/sda/login' => 'sda/users/sessions#create', :as => :user_session
      get '/sda/logout' => 'sda/users/sessions#destroy', :as => :sda_logout
               
    end

   root 'main#index'
  

      
 
  resources :website_locales
  resources :websites
  resources :brands, only: [:index, :show]
  
    resources :news, only: [:index, :show] do
      collection { get :archived }
    end
    
  resources :users,
            :product_sub_categories,
            :product_categories
            
    
    get "/serve-me-this/:id" => "serve_me_this#download_media", as: :serve_me_this
    
            
    
    get '/tnc' => redirect('/tnc/freedom-to-mix')
    get '/tnc/freedom-to-mix' => 'main#freedom_to_mix_sweepstakes', as: :freedom_to_mix_sweepstakes
            
            
    
    get '/get-started/ui' => 'get_started#ui', as: :get_started_ui
    get '/get-started/signature' => 'get_started#signature', as: :get_started_signature
    get '/get-started' => 'get_started#index', as: :get_started
    
    
    
    
    get "/media" => "media#index", as: :media
    get "/videos(/:id)" => "videos#index", as: :videos
    get "videos/play/:id" => "videos#play", as: :play_video
    get "/software" => "software#index", as: :software
    
    
    get "/whats-on" => "whats_on#index", as: :whats_on
    get "/mixing-with-professionals" => "mixing_with_professionals#index", as: :mixing_with_professionals
    get "/mixing-with-professionals/training-courses" => "mixing_with_professionals#training_courses", as: :training_courses
    get "/whats-on/events" => "whats_on#events", as: :events
    get "/whats-on/soundcraft-users"=> "whats_on#soundcraft_users", as: :soundcraft_users
    get "/whats-on/rental" => "whats_on#rental", as: :rental   
    
    
    match '/where-to-buy(/:zip)' => 'where_to_buy#index', as: :where_to_buy , via: :all

    
    get "/support" => "support#index", as: :support
    match "/support/contact-us" => "support#contact_us", as: :contact_us, via: :all
    match "/support/product-registration" => "support#product_registration", as: :product_registration, via: :all
    get "/support/warranty" => "support#warranty", as: :warranty
    get "/support/tech-support" => "support#tech_support", as: :tech_support
    
    
    get "/experience-harman" => "main#experience_harman", as: :experience_harman
    get "/about-soundcraft" => "main#about_soundcraft", as: :about_soundcraft
    get '/imprint' => 'main#imprint', as: :imprint
    get '/legal' => 'main#legal', as: :legal
    get '/privacy-policy' => 'main#privacy_policy', as: :privacy_policy
    
    get '/mixing-with-professionals/mwp-calendar' => 'mixing_with_professionals#mwp_calendar', as: :mwp_calendar
    get '/guide-to-mixing' => 'guide_to_mixing#index', as: :guide_to_mixing
    get '/mailing-list' => 'main#mailing_list', as: :mailing_list
    
    match '/sitemap(.:format)' => 'main#sitemap', as: :sitemap, via: :all
    match '/search' => 'main#search', as: :search, via: :all
    get '/careers' => 'main#careers', as: :careers
    
    
    
    get '/products/mixing-consoles' => 'products#mixing_consoles', as: :mixing_consoles
    get '/products/stageboxes' => 'products#stageboxes', as: :stageboxes
    get '/products/option-cards' => 'products#option_cards', as: :option_cards
    get '/products/recording-interfaces' => 'products#recording_interfaces', as: :recording_interfaces
    get '/products/plugins' => 'products#plugins', as: :plugins
    get '/products/mobile-apps' => 'products#mobile_apps', as: :mobile_apps
    
    get '/products/mixing-consoles/vi-series' => 'products#vi_series', as: :vi_series
    get '/products/mixing-consoles/si-series' => 'products#si_series', as: :si_series
    get '/products/mixing-consoles/ui-series' => 'products#ui_series', as: :ui_series
    get '/products/mixing-consoles/signature-series' => 'products#signature_series', as: :signature_series
    get '/products/mixing-consoles/signature-mtk-series' => 'products#signature_mtk_series', as: :signature_mtk_series
    get '/products/mixing-consoles/gb-series' => 'products#gb_series', as: :gb_series
    get '/products/mixing-consoles/epm-efx-mpm-mfx' => 'products#epm_efx_mpm_mfx', as: :epm_efx_mpm_mfx
    get '/products/mixing-consoles/multi-purpose' => 'products#multi_purpose', as: :multi_purpose
    get '/products/mixing-consoles/china-only' => 'products#china_only', as: :china_only
    
    get '/products/recording-interfaces/signature-mtk-series' => redirect('/products/mixing-consoles/signature-mtk-series')
    
    
    resources :products, only: [:index, :show] 
    
    
     
    match '/' => 'main#index', as: :locale_root, via: :all
    
    match '/:controller(/:action(/:id))', via: :all
    match "*custom_route" => "pages#show", as: :custom_route, via: :all

end

app/views/shared/_add_this.html.erb
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=soundcraftuk" async="async"></script>
<div class="addthis_sharing_toolbox"></div>

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2349447-1']);
  _gaq.push(['_setDomainName', 'soundcraft.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_buynow.html.erb
<ul class="large-block-grid-6 small-block-grid-3">

<% product.preferred_retailer_links.each do |prl| %>
	<li class="retailer_logo preferred">
		<%= render "shared/online_retailer_link", orl: prl %>
	</li>
<% end %>

<% product.randomized_retailer_links.each do |orl| %>
	<li class="retailer_logo">
		<%= render "shared/online_retailer_link", orl: orl %>
	</li>
<% end %>

</ul>

app/views/shared/_column_for_news.html.erb
<div class="row">
	<div class="large-12 columns">
		<% big_news = [@news.shift, @news.shift] %>
		<ul class="large-block-grid-2 small-block-grid-2 image-grid">
			<% big_news.each do |news| %>
				<li class="featured news-with-popover">
			  	<%= link_to news do %>
			  		<% if news.news_photo_file_name.blank? %>
						<%= translate_content(news, :title) %>
			  		<% else %>
			  			<%= image_tag(news.news_photo.url(:small_square)) %>
			  			<div class="popover"><h3><%= translate_content(news, :title) %></h3></div>
			  		<% end %>
			  		<h4><%=l news.post_on, format: :long %></h4>
			  	<% end %>
			  </li>
			<% end %>
		</ul>
	</div>
	<div class="large-12 columns">
		<ul class="large-block-grid-4 small-block-grid-4 image-grid">
		<% @news.each do |news| %>
		  <li class="secondary news-with-popover">
		  	<%= link_to news do %>
		  		<% if news.news_photo_file_name.blank? %>
					<%= translate_content(news, :title) %>
		  		<% else %>
		  			<%= image_tag(news.news_photo.url(:thumb_square)) %>
		  			<div class="popover"><h5><%=truncate translate_content(news, :title), length: 50 %></h5></div>
		  		<% end %>
				<h4><%=l news.post_on, format: :short %></h4>
		  	<% end %>
		  </li>
		<% end %>
		</ul>
	</div>
</div>

app/views/shared/_column_for_news_and_reviews.html.erb
  <div class="row">
  	<div class="large-10 large-offset-1 columns">
  		<ul data-orbit data-options="slide_number:false; pause_on_hover:false; navigation_arrows:false;">
		<% @news.each do |news| %>
		  <li>
		  	<div class="large-8 large-offset-2 small-8 small-offset-2 columns">
				<h3><%= link_to translate_content(news, :title), news %></h3>
				<h3 class="subheader"><small><%=l news.post_on, format: :short %></small></h3>
		  	</div>
		  </li>
		<% end %>
		</ul>
	</div>
  </div>

app/views/shared/_column_for_youtube.html.erb
<% if website.value_for("youtube") %>
	<h2><%= social_media_links 'youtube', style: 'circle', size: '48x48' %> 
		<%= link_to t('titles.youtube_channel', brand: website.brand_name), videos_path %>
	</h2>
	<%= cache ["youtube_feed", website.brand, I18n.locale] do %>
		<%= youtube_feed(@youtube, 'horizontal') %>
	<% end %>
<% end %>

app/views/shared/_footer_jquery_muse.html.erb
<script type="text/javascript">
   window.jQuery || document.write('\x3Cscript src="js/muse/jquery-1.8.3.min.js" type="text/javascript">\x3C/script>');
</script>
    <script src="js/muse/museutils.js" type="text/javascript"></script>
  <script src="js/muse/jquery.scrolleffects.js" type="text/javascript"></script>
  <script src="js/muse/jquery.watch.js" type="text/javascript"></script>
	<script>
$(document).ready(function(){

$('#mwp1').registerPositionScrollEffect([{"in":[-Infinity,100],"speed":[4,-4]},{"in":[10,Infinity],"speed":[0,0]}]);
$('#mwp2').registerPositionScrollEffect([{"in":[-Infinity,100],"speed":[-4,-4]},{"in":[10,Infinity],"speed":[0,0]}]);
$('#mwp3').registerPositionScrollEffect([{"in":[-Infinity,120],"speed":[4,-4]},{"in":[10,Infinity],"speed":[0,0]}]);
$('#mwp4').registerPositionScrollEffect([{"in":[-Infinity,120],"speed":[-4,-4]},{"in":[10,Infinity],"speed":[0,0]}]);

$('#mwp1').registerOpacityScrollEffect([{"fade":50,"in":[-Infinity,50],"opacity":0},{"opacity":100,"in":[0,0]},{"fade":50,"in":[0,Infinity],"opacity":100}]);
$('#mwp2').registerOpacityScrollEffect([{"fade":50,"in":[-Infinity,50],"opacity":0},{"opacity":100,"in":[0,0]},{"fade":50,"in":[0,Infinity],"opacity":100}]);
$('#mwp3').registerOpacityScrollEffect([{"fade":50,"in":[-Infinity,50],"opacity":0},{"opacity":100,"in":[0,0]},{"fade":50,"in":[0,Infinity],"opacity":100}]);
$('#mwp4').registerOpacityScrollEffect([{"fade":50,"in":[-Infinity,50],"opacity":0},{"opacity":100,"in":[0,0]},{"fade":50,"in":[0,Infinity],"opacity":100}]);


});
</script>

app/views/shared/_footer_jquery_scrollup.html.erb
<script>
$(document).ready(function(){
	
/* Check to see if the window is top if not then display button */
$(window).scroll(function(){
	if ($(this).scrollTop() > 500) {
		$('.scrollToTop').fadeIn();
	} else {
		$('.scrollToTop').fadeOut();
	}
});

/* Click event to scroll to top */
$('.scrollToTop').click(function(){
	$('html, body').animate({scrollTop : 0},500);
	return false;
});
	
/* panel to top for the product main panels */	
$('.panelToTop').click(function(){
	$('html, body').animate({scrollTop : 800},500);
	return true;
});

$('.scrollToTop').hide();


});
</script>

app/views/shared/_form_contacts_section.html.erb
<div class="web-form-section">
<div class="row" >
	<div class="small-6 columns">
	 	<div>	
		 	<%= cache ["registerable_salutation", website.brand, I18n.locale] do %>
			<%= f.label "Title" %>
			<%= f.collection_select :salutation_id, 
				Salutation.all_for_website(),
				:id, :en, prompt: true, :class =>'50' %>
			<% end %>	
		</div>
		<div>
			<label>First Name <small class="color-accent bold">(required field)</small></label>
			<%= f.text_field :first_name, required: '', pattern: "[a-zA-Z]+" %>
			
    		<small class="error">First Name is required.</small>
		</div>
		<div>
			<label>Last Name <small class="color-accent bold">(required field)</small></label>
			<%= f.text_field :last_name, required: '', pattern: "[a-zA-Z]+" %>
			
    		<small class="error">Last Name is required.</small>
		</div>
		<div>
			<%= f.label :company %>
			<%= f.text_field :company %>
		</div>
		<div>
			<%= f.label :job_title %>
			<%= f.text_field :job_title %>
		</div>
		<div>
			<label>Email Address <small class="color-accent bold">(required field)</small></label>
			<%= f.text_field :email %>
    		<small class="error">Email address is required.</small>
		</div>	
		<div>
			<%= f.label :phone %>
			<%= f.text_field :phone %>
		</div>
	</div>	
	<div class="small-6 columns">
		<div>
			<%= f.label :address1 %>
			<%= f.text_field :address1 %>
		</div>
		<div>
			<%= f.label :address2 %>
			<%= f.text_field :address2 %>
		</div>
		<div>
			<%= f.label :city %>
			<%= f.text_field :city %>
		</div>
		<div>
			<%= f.label :county %>
			<%= f.text_field :county %>
		</div>
		<div>
			<%= f.label :post_code %>
			<%= f.text_field :post_code %>
		</div>
		<div>
			<%= cache ["registerable_countries", website.brand, I18n.locale] do %>
			<label>Country <small class="color-accent bold">(required field)</small></label>
			<%= f.collection_select :country_id, 
			Country.all_for_website(),
			:id, :name, prompt: true, required: '' %>
			
    		<small class="error">Email is required.</small>
			<% end %>
		</div>
	</div>
</div>	
</div>

app/views/shared/_form_enquiries_section.html.erb
<%= f.fields_for :users_enquiries do |builder| %>
<div class="web-form-section">
	<div class="row">
		<div class="small-6 columns">
			<%= cache ["registerable_enuiries", website.brand, I18n.locale] do %>
			<label>Enquiry Type <small class="color-accent bold">(required field)</small></label>
			<%= builder.collection_select :enquiry_id, 
			Enquiry.all_for_website(), 
			:id, :name, prompt: true, required: '' %>
			
			<small class="error">Enquiry type is required.</small>
			<% end %>
		</div>
		<div class="small-6 columns">
			<%= cache ["registerable_products", website.brand, I18n.locale] do %>
			<%= builder.label :product_id %>
			<%= builder.collection_select :product_id, 
			Product.all_for_website_registration(), 
			:id, :name, prompt: true %>
			<% end %>
		</div>
	</div>
	<div width="60%">
		<label>Subject <small class="color-accent bold">(required field)</small></label>
		<%= builder.text_field :subject, required: '', pattern: "[a-zA-Z]+" %>
		
		<small class="error">Subject is required.</small>
	</div>
	<div width="100%">
		<label>Message <small class="color-accent bold">(required field)</small></label>
		<%= builder.text_area :message, size: "40x5" %>
		
		<small class="error">Subject is required.</small>
	</div>
</div>
<% end %>

app/views/shared/_form_optins_section.html.erb
<div  class="web-form-section">
	<div>
	<%= f.check_box :soundcraft_optin, checked: true %>
	<span class="color-gray-medium margin-left"><%= "Would you like to received interested products and services from Soundcraft" %></span>
</div>
<div >
	<%= f.check_box :third_party_optin %>
	<span class="color-gray-medium margin-left"><%= "Would you like to received interested products and services from other harman companies?" %></span>
</div>
</div>

app/views/shared/_form_products_section.html.erb
<%= f.fields_for :users_products do |builder| %>
<div class="web-form-section" >
<div class="row">
	<div class="small-6 columns">
		
		<div>
			<%= cache ["registerable_products", website.brand, I18n.locale] do %>
			<label>Product <small class="color-accent">(required field)</small></label>
			<%= builder.collection_select :product_id, 
			Product.all_for_website_registration(), 
			:id, :name, prompt: true, required: '' %>
			
    		<small class="error">Product is required.</small>
			<% end %>	
		</div>
		<div>
			<label>Serial Number <small class="color-accent">(required field)</small></label>
			<%= builder.text_field :serial, required: '', pattern: "[a-zA-Z]+" %>
			
    		<small class="error">Serial Number is required.</small>
		</div>
		<div>&nbsp;</div>
		<div>
			<%= cache ["registerable_applications", website.brand, I18n.locale] do %>
			<label>What is your main application for the product?</label>
			<%= builder.collection_select :application_id, 
			Application.all_for_website_registration(), 
			:id, :name, prompt: true %>
			<% end %>	
		</div>
		<div>
			<label>What influenced you on your purchase?</label>
			<%= builder.text_field :influence %>
		</div>
		<div>
			<label>How did you hear about the product?</label>
			<%= builder.text_field :hear_from %>
		</div>
		
	</div>	
	<div class="small-6 columns">
		<div>
			<label>Purchase Date <small class="color-accent">(required field)</small></label>
			<%= builder.date_field :purchased_date, required: '' %>
			
    		<small class="error">Purchase date is required.</small>
		</div>
		<div>
			<label>Who did you buy the product from?</label>
			<%= builder.text_field :purchased_from %>
		</div>
		<div>
			<label>How much did you paid?</label>
			<%= builder.text_field :purchased_amount %>
		</div>
	</div>
</div>
<div>
	<label>Is there anything else you would like to tell us?</label>
	<%= builder.text_area :comment, size: "40x5" %>
<br />
</div>
</div>
<% end %>	

app/views/shared/_homepage_adobe_edge_runtime.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<script type="text/javascript" charset="utf-8" src="http://animate.adobe.com/runtime/5.0.1/edge.5.0.1.min.js"></script>
<style>
    .edgeLoad-EDGE-vi3000 { visibility:hidden; }
</style>
<script>
   AdobeEdge.loadComposition('<%= s3_homepage_edge_url %>', 'EDGE-vi3000', {
    scaleToFit: "both",
    centerStage: "horizontal",
    minW: "0",
    maxW: "undefined",
    width: "1200px",
    height: "500px"
}, {dom: [ ]}, {
    dom: [

    ],
    style: {
        '${symbolSelector}': {
            isStage: true,
            rect: [undefined, undefined, '1200px', '500px'],
            fill: ["rgba(0,0,0,1)"]
        }
    }
});
</script>

app/views/shared/_newsletter_signup.html.erb
<div >
	<form action="#" method="post">
		<h4><%= t('news_signup')%></h4>
  <div class="row">
    <div class="large-12 columns">
      <div class="row collapse">
        <div class="small-10 columns">
          <input type="text" placeholder="email address">
        </div>
        <div class="small-2 columns">
          <input type="submit" value="Go" class="button postfix">
        </div>
      </div>
    </div>
  </div>
	</form> 
</div>